name: Deployment CI

on: ['deployment']
  
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # Set deployment status to in_progress
      # - uses: actions/github-script@0.4.0
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     # in_progress status is only available in preview api, for some reason
      #      # even setting the preview here doesn't work though
      #     previews: ant-man-preview
      #     script: |
      #       github.repos.createDeploymentStatus({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         deployment_id: context.payload.deployment.id,
      #         state: 'in_progress'
      #       })
      # do some deploying...
      - name: Deploy
        # we have access of the app version set by the master workflow.
        # We could use that to fetch the built artifact from somewhere.
        run: echo deploy ${{ github.event.deployment.payload.app_version }}
      # Update deployment status
      - name: Report successful deployment
        if: success()
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # Cf. https://octokit.github.io/rest.js/
          script: |
            github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.payload.deployment.id,
              state: 'success'
            })
      - name: Report failed deployment
        if: failure()
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # Cf. https://octokit.github.io/rest.js/
          script: |
            github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.payload.deployment.id,
              state: 'failure'
            })            
