name: Deployment CI

on: ['deployment']
  
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # do some deploying...
      - name: Deploy
        run: echo deploy
      - uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(context)
      #res = await console.log(res.data.id)
      # do the deployment ... possibly in a different workflow that listens to 'deployment' event
      # - uses: actions/github-script@0.4.0
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       github.repos.createDeploymentStatus({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: context.sha,
      #         required_contexts: [],
      #         environment: 'integration'
      #       })
