name: Manual trigger workflow

on:
  push:
    tags:
      - 'deploy_test'
  workflow_dispatch:
    inputs:
      testInput:
        description: 'Test Input (not needed)'
        required: false
        default: 'foobar'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # - name: Drop the command tag
      #   uses: actions/github-script@0.4.0
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     # Cf. https://octokit.github.io/rest.js/
      #     script: |
      #       github.git.deleteRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: context.ref.replace('refs/', ''),
      #         sha: context.sha,
      #       })

      - uses: actions/checkout@v1

      - name: print sha
        run: "echo sha: ${{ github.sha }}, ref: ${{ github.ref }}"

      - name: print readme
        run: "cat README.md"
