name: poc CI

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Drop the command tag
        uses: actions/github-script@0.4.0        
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # Cf. https://octokit.github.io/rest.js/
          script: |
            bla = await github.graphql(`
            {
              repository(name: "github-actions-poc", owner: "adnovum") {
                registryPackagesForQuery(first: 100) {
                  edges {
                    node {
                      id,name, versions(first:100){
                        edges {
                          node {
                            id,version,updatedAt
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            `)
            let cutoff = new Date(new Date().getTime() - 30 * 86400000)
            console.log(cutoff)
            for (let pkg of bla.repository.registryPackagesForQuery.edges) { 
              for (let ver of pkg.node.versions.edges) { 
                let dt = new Date(ver.node.updatedAt)
                if (dt <= cutoff) {
                  console.log('', ver.node)
                }
              }
            }