name: poc CI

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Drop the command tag
        uses: actions/github-script@0.4.0        
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # Cf. https://octokit.github.io/rest.js/
          script: |
            bla = await github.graphql(`
            {
              repository(name: "github-actions-poc", owner: "adnovum") {
                registryPackagesForQuery(first: 20) {
                  edges {
                    node {
                      id,name, versions(first:20){
                        edges {
                          node {
                            id,version,updatedAt
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            `)
            for (let edge of bla.repository.registryPackagesForQuery.edges) { 
              console.log('', edge)
            }