name: Release CI

on:
#  release:
#    # there is also 'created', but not clear what the difference is.
#    # 'created' isn't triggered when creating a release draft.
#    types: [published]
  push:
    tags:
      - 'release-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Determine version to deploy
        id: determine_version
        run: git tag --points-at HEAD | grep '^deployed_test-' | sed 's/^ci-/::set-output name=version::/'

      # instead of rebuilding, we should fetch the artifact based on the determined version.
      - name: Build
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: released-${{ steps.determine_version.outputs.version }}
          release_name: Release ${{ steps.determine_version.outputs.version }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # No glob support, no way to read a file or stdout for the version used
          asset_path: ./build/distributions/release.zip
          asset_name: release.zip
          asset_content_type: application/zip